fix pc entry creation for load_collection
Open-EO/openeo-grassgis-driver pull request #155
Opened 2022-11-10 14:00 UTC by metzm

Handling of the new collection type was missing in one place

2022-11-10 14:32 UTC, griembauer approved these changes

2022-11-10 14:39 UTC, griembauer requested changes
There is still a problem with the correct passing of the `bands` parameter to `t.in.eoarchive`: 
`"bands=S2_B4', 'S2_B8"`
--> `"ERROR: Value <S2_B4'> out of range for parameter <bands>"`

2022-11-10 14:41 UTC, griembauer commented on src/openeo_grass_gis_driver/actinia_processing/load_collection_process.py
> +                inputs.append({"param": "bands", "value": ("', '").join(bands)})
This works assuming that a `load_collection` process could look like this:

2022-11-17 06:24 UTC, griembauer approved these changes

2022-11-17 08:21 UTC, mmacata approved these changes

2022-11-17 09:17 UTC, merged