Create + use actinia processes dict with only one returns
Open-EO/openeo-grassgis-driver pull request #87
Opened 2021-04-29 14:05 UTC by mmacata

While GRASS GIS modules can have multiple outputs, the openEO API allows only one. This PR duplicates the ACTINIA_PROCESS_DESCRIPTION_DICT and manipulates the copy to split up modules with multiple outputs. Instead of an array of outputs, the module then has only one output object.

Example: 
`r.slope.aspect` will not appear as a single module but as many for each of its outputs:

```
{
	"id": "r.slope.aspect_slope",
	"parameters": [...],
	"returns": {
		"description": "Name for output slope raster map. ",
		"name": "slope",
		"optional": true,
		"schema": {
			"subtype": "cell",
			"type": "string"
		}
	}
},
{
	"id": "r.slope.aspect_aspect",
	"parameters": [...],
	"returns": {
		"description": "Name for output aspect raster map. ",
		"name": "aspect",
		"optional": true,
		"schema": {
			"subtype": "cell",
			"type": "string"
		}
	}
},
...
```

Hint:
To see this change in action, the actinia module filters need to be deployed in the used actinia instance. The current configured instance https://actinia-dev.mundialis.de is not yet up-to-date. These changes won't break things though.

For each touched file the lint errors were fixed.

2021-04-29 15:32 UTC, huhabla commented
So openEO API still allows only a single output for a process?

2021-04-30 07:36 UTC, mmacata commented
As per API specification `returns` is an object with `description` and `schema` and not an array of objects - yes, only a single output for predefined processes is allowed.

2021-04-30 13:07 UTC, metzm commented on src/openeo_grass_gis_driver/register_actinia_processes.py
> +        print("... successfully registered modules!")
Is this `print()` left-over debugging code?

2021-04-30 13:19 UTC, metzm requested changes
Looks good to me, but I guess the new `print()` line needs to be removed before merging.

2021-04-30 13:28 UTC, metzm approved these changes
Thanks for the explanation, ready to merge.

2021-04-30 13:35 UTC, merged